# =====================================================
#  VeloTab v2.0.0 - The Modular Revolution
#  Creado por ItzUsman (itzusm.netlify.app)
# =====================================================

# Idioma global (es / en)
language: es

# --- MÓDULOS ---
# Habilita o deshabilita las carpetas de configuración.
modules:
  tablist: true
  scoreboard: true
  chat: true
  bossbar: false
  actionbar: false
  security: true
  discord: false
  animations: true

# --- ACTUALIZACIONES ---
update_checker: true
auto_update: false

# --- SINCRONIZACIÓN ---
network_sync:
  enable: true
