# =====================================================
#  VeloTab v2.1.0 - The Premium Experience
#  Creado por ItzUsman (itzusm.netlify.app)
# =====================================================

# Idioma global (es / en)
language: es

# --- MÓDULOS ---
modules:
  tablist: true
  scoreboard: true
  chat: true
  bossbar: false
  actionbar: false
  security: true
  discord: false
  animations: true
  nametags_pro: false # Requiere ProtocolLib

# --- BASE DE DATOS ---
# Sincroniza datos entre servidores (Toggle, Tags, etc.)
database:
  enable: false
  type: "MYSQL" # MYSQL, SQLITE
  host: "localhost"
  port: 3306
  name: "velotab"
  user: "root"
  password: ""
  ssl: false

# --- ACTUALIZACIONES ---
update_checker: true
auto_update: false

# --- SINCRONIZACIÓN ---
network_sync:
  enable: true
