name: VeloTab
version: '1.7.0'
main: me.itzusman.velotab.paper.VeloTabPaperPlugin
api-version: '1.20'
author: ItzUsman
website: itzusm.netlify.app
description: >
  VeloTab: Suite completa de TabList, Scoreboard y Seguridad de comandos.
  Creado por ItzUsman.
softdepend: [LuckPerms, PlaceholderAPI]

commands:
  velotab:
    description: Comando principal de VeloTab.
    permission: velotab.admin
    usage: /<command> <info|reload>

permissions:
  velotab.admin:
    description: Permite administrar el plugin.
    default: op
  velotab.bypass:
    description: Salta todos los filtros de comandos.
    default: op
