<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>me.itzusman</groupId>
        <artifactId>VeloTab-Parent</artifactId>
        <version>1.6.1</version>
    </parent>

    <artifactId>VeloTab</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>me.itzusman</groupId>
            <artifactId>VeloTab-Common</artifactId>
            <version>1.6.1</version>
        </dependency>
        <dependency>
            <groupId>me.itzusman</groupId>
            <artifactId>VeloTab-Paper</artifactId>
            <version>1.6.1</version>
        </dependency>
        <dependency>
            <groupId>me.itzusman</groupId>
            <artifactId>VeloTab-Velocity</artifactId>
            <version>1.6.1</version>
        </dependency>
        <!-- BungeeCord se omite si da problemas de repo, pero lo ideal es incluirlo -->
    </dependencies>

    <build>
        <finalName>VeloTab-v1.6.1</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
